import type { UserPreferences } from './types';
import {
  NotificationType,
  NavigationTabAppearance,
  HomeShowOption,
  SortOption,
  ColorMode,
  Theme,
  EmojiSkinTone,
  MarkAsReadBehavior,
  SearchSortDefault,
} from './types';

export const DEFAULT_PREFERENCES: UserPreferences = {
  notifications: {
    type: NotificationType.ALL_MESSAGES,
    differentMobileSettings: false,
    huddles: true,
    threadReplies: true,
    keywords: '',
  },
  vip: {
    allowFromVIPs: false,
    vipList: [],
  },
  navigation: {
    showHome: true,
    showDMs: true,
    showActivity: true,
    showFiles: true,
    showTools: false,
    tabAppearance: NavigationTabAppearance.ICONS_AND_TEXT,
  },
  home: {
    showChannelOrganization: true,
    showActivityDot: true,
    alwaysShowUnreads: false,
    alwaysShowHuddles: true,
    alwaysShowThreads: true,
    alwaysShowDraftsSent: true,
    alwaysShowDirectories: true,
    show: HomeShowOption.ALL_CONVERSATIONS,
    sort: SortOption.ALPHABETICALLY,
    showProfilePhotos: true,
    separatePrivateChannels: false,
    separateDirectMessages: false,
    moveUnreadMentions: true,
    organizeExternalConversations: true,
    displayMutedItems: false,
  },
  appearance: {
    font: 'Lato (Default)',
    colorMode: ColorMode.SYSTEM,
    theme: Theme.AUBERGINE,
    displayTypingIndicator: true,
    displayColorSwatches: true,
    emojiSkinTone: EmojiSkinTone.DEFAULT,
    displayEmojiAsText: false,
    showJumbomoji: true,
    convertEmoticons: true,
    showOneClickReactions: true,
    customReactionEmojis: ['white_check_mark', 'speech_balloon', 'raised_hands'],
  },
  messagesMedia: {
    showImagesFiles: true,
    showImagesLinked: true,
    showImagesLarge: false,
    showTextPreviews: true,
  },
  languageRegion: {
    language: 'English (US)',
    timezone: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    autoTimezone: true,
    keyboardLayout: 'English (US)',
    spellcheck: true,
  },
  accessibility: {
    simplifiedLayoutMode: false,
    underlineLinks: false,
    tabPreviews: true,
    autoPlayAnimations: true,
    messageFormat: 'sender_message_date',
    announceIncomingMessages: true,
    readEmojiReactions: true,
    playEmojiSound: true,
  },
  markAsRead: {
    behavior: MarkAsReadBehavior.START_WHERE_LEFT,
    promptOnMarkAll: true,
  },
  audioVideo: {
    microphoneDevice: 'default',
    speakerDevice: 'default',
    cameraDevice: 'default',
  },
  privacyVisibility: {
    slackConnectDiscoverable: true,
    contactSharing: 'all',
    blockedInvitations: [],
    hiddenPeople: [],
  },
  slackAI: {
    streamSummaries: true,
  },
  advanced: {
    whenTypingCodeEnterShouldNotSend: false,
    formatMessagesWithMarkup: false,
    enterBehavior: 'send',
    ctrlFStartsSearch: false,
    searchShortcut: 'cmd_k',
    excludeChannelsFromSearch: [],
    searchSortDefault: SearchSortDefault.MOST_RELEVANT,
    confirmUnsend: true,
    confirmAwayToggle: true,
    warnMaliciousLinks: true,
    warnExternalFiles: true,
    warnExternalCanvases: true,
    channelSuggestions: true,
    surveys: true,
  },
  streamSummaryResults: true,
};

